name: CI Shisho demo

on:
  pull_request:
    branches: [master]

jobs:
  # Install dependencies once, and use them for all other jobs
  install-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Use Node.js version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm ci

  # Check for linting ( using ESlint )
  lint-check:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Use Node.js version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true

  # execute unit tests  
  unit-test:
      runs-on: ubuntu-latest
      needs: install-dependencies
      steps:
        - name: Checkout commit
          uses: actions/checkout@v2
        - name: Use Node.js version 12.x
          uses: actions/setup-node@v1
          with:
            node-version: "12.x"
        - name: Restore dependencies
          uses: actions/cache@v2
          id: cache-dependencies
          with:
            path: node_modules
            key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - run: npm run test -- --coverage
          env:
            CI: true 

  # Scan packages for vulnerabilities using Snyk, requires unit-test & lint-check jobs to pass 
  scan_packages:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Use Node.js version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
