name: CI Shisho demo

on:
  pull_request:
    branches: [master]

jobs:
  check-integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project content
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    
      - name: Install nodeJS with version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run test -- --coverage 
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
      # - name: Build project
      #   if: ${{ github.event_name == 'push'}}
      #   run: npm run build
      # - name: Deploy to heroku
      #   if: ${{ github.event_name == 'push'}}
      #   uses: akhileshns/heroku-deploy@v3.4.6
      #   with:
      #     heroku_api_key: '${{ secrets.HEROKU_API_KEY }}'
      #     heroku_app_name: 'shisho-demo'
      #     heroku_email: '${{ secrets.HEROKU_EMAIL }}'
      #     buildpack: "https://github.com/heroku/heroku-buildpack-static.git -a shisho-demo"
