name: CI Shisho demo

on:
  pull_request:
    branches: [master]

jobs:
  check-integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project content
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    
      - name: Install nodeJS with version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run test -- --coverage
        env:
          CI: true 
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
